version: 2
jobs:
  test:
    docker:
      - image: circleci/node:16.6.0
    steps:
      - checkout
      - run: 
          command: npm install && npm test
          no_output_timeout: 12m
workflows:
  version: 2
  test:
    jobs:
      - test
